config/routes.rb
require 'sidekiq/web'
NovelServer::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'novels#index'
  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  

  resources :novels do 
    collection do
      put 'search'
      put 'update_novel'
      get 'auto_crawl_info'
      put 'auto_crawl'
    end
    member do
      get 'invisiable_articles'
      get 'set_all_articles_to_invisiable'
      put 'set_artlcles_to_invisiable'
      post 'change'
      get 'recrawl_all_articles'
      get 'recrawl_blank_articles'
    end
  end

  resources :articles do
    collection do
      get 're_crawl'
      put 'crawl_text_onther_site'
      put 'reset_num'
      put 'search_by_num'
    end
  end

  resources :ships, except: [:index,:show] do
    collection do
      get 'this_week_hot'
      get 'this_month_hot'
      get 'hot'
    end
  end

  resources :recommend_categories
  resources :recommend_category_novel_ships


  namespace :api do
    get 'status_check' => 'api#status_check'
    get 'version_check' => 'api#version_check'
    namespace :v1 do

      resources :recommend_categories, only: [:index]
      resources :categories, :only => [:index]
      resources :novels,:only => [:index, :show] do
        collection do
          get 'category_hot'
          get 'category_this_week_hot'
          get 'category_recommend'
          get 'category_latest_update'
          get 'category_finish'
          get 'all_novel_update'
          get 'hot'
          get 'this_week_hot'
          get 'this_month_hot'
          get 'search'
          get 'elastic_search'
          get 'classic'
          get 'classic_action'
          get 'collect_novels_info'
          get 'recommend_category_novels'
          get 'new_uploaded_novels'
        end
        member do 
          get 'detail_for_save'
        end
      end
      resources :articles,:only => [:index, :show] do
        collection do 
          get 'next_article'
          get 'previous_article'
          get 'articles_by_num'
          get 'next_article_by_num'
          get 'previous_article_by_num'
          # get 'db_transfer_index'
        end
      end

      resources :users, :only => [:create] do
        collection do
          put 'update_novel'
          get 'get_novels'
          get 'back_up_info'
        end
      end
    end
  end
end

app/models/recommend_category.rb
class RecommendCategory < ActiveRecord::Base
  attr_accessible :name

  has_many :recommend_category_novel_ships
  has_many :novels, :through => :recommend_category_novel_ships
  
end

app/controllers/api/v1/recommend_categories_controller.rb
class Api::V1::RecommendCategoriesController < Api::ApiController

  def index
    @categories = RecommendCategory.select("id, name").all
  end
end

app/controllers/recommend_categories_controller.rb
class RecommendCategoriesController < ApplicationController  
  
  def index
    @categories = RecommendCategory.paginate(:page => params[:page], :per_page => 20)
  end

  def destroy
    @category = RecommendCategory.find(params[:id])
    RecommendCategoryNovelShip.delete_all("recommend_category_id = #{@category.id}")
    @category.destroy
    redirect_to :controller => 'recommend_categories', :action => 'index'
  end

  def edit
    @category = RecommendCategory.find(params[:id])
  end

  def update
    @category = RecommendCategory.find(params[:id])
    if @category.update_attributes(params[:recommend_category])
      redirect_to :action => 'index'
    else
      render :action => "edit" 
    end
  end

  def show
    @category = RecommendCategory.find(params[:id])
  end

  def new
    @category = RecommendCategory.new
  end

  def create
    category = RecommendCategory.new(params[:recommend_category])
    category.save
    redirect_to :controller => 'recommend_categories', :action => 'index'
  end
end

app/views/recommend_categories/edit.html.erb
<%= form_for @category do |f|%>

  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.submit %>

<% end %>

app/views/recommend_categories/index.html.erb
<h1>Listing categories</h1>

<%= will_paginate @categories %>
<br>
<br>
<table>
  <tr>
    <th>推薦類別名</th>
    <th>類別小說數</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.novels.size %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_recommend_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<br />

<%= link_to '新增類別', new_recommend_category_path %> <br>

app/views/recommend_categories/new.html.erb
<h1>新增類別</h1>

<%= form_for(@category) do |f| %>

    <%= f.label "類別名稱" %>:
    <%= f.text_field :name %>

    <%= f.submit "新增"%>
<% end %>

<br>
<br>
<br>
<%= link_to '回到類別', recommend_categories_path %>

app/views/recommend_categories/show.html.erb
<h1>Listing category novels</h1>

類別名: <%= @category.name %> 
<br>
<%= link_to '新增小說', new_recommend_category_novel_ship_path(recommend_category: @category.id) %> <br>
<br>
<table>
  <tr>
    <th>推薦書名</th>
    <th>類別名</th>
    <th>書id</th>
  </tr>

<% @category.recommend_category_novel_ships.each do |ship| %>
  <tr>
    <% if ship.novel  %>
      <td><%= ship.novel.name %></td>
      <td><%= (ship.novel.category)? ship.novel.category.name : "沒有類別" %></td>
      <td><%= ship.novel.id %></td>
      <td><%= link_to 'Destroy', ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%else %>
      <%= ship.id %>
      <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新增小說', new_recommend_category_novel_ship_path(recommend_category: @category.id) %> <br>