config/routes.rb
require 'sidekiq/web'
NovelServer::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'novels#index'
  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  

  resources :novels do 
    collection do
      put 'search'
      put 'update_novel'
      get 'auto_crawl_info'
      put 'auto_crawl'
    end
    member do
      get 'invisiable_articles'
      get 'set_all_articles_to_invisiable'
      put 'set_artlcles_to_invisiable'
      post 'change'
      get 'recrawl_all_articles'
      get 'recrawl_blank_articles'
    end
  end

  resources :articles do
    collection do
      get 're_crawl'
      put 'crawl_text_onther_site'
      put 'reset_num'
      put 'search_by_num'
    end
  end

  resources :ships, except: [:index,:show] do
    collection do
      get 'this_week_hot'
      get 'this_month_hot'
      get 'hot'
    end
  end

  resources :recommend_categories
  resources :recommend_category_novel_ships


  namespace :api do
    get 'status_check' => 'api#status_check'
    get 'version_check' => 'api#version_check'
    namespace :v1 do

      resources :recommend_categories, only: [:index]
      resources :categories, :only => [:index]
      resources :novels,:only => [:index, :show] do
        collection do
          get 'category_hot'
          get 'category_this_week_hot'
          get 'category_recommend'
          get 'category_latest_update'
          get 'category_finish'
          get 'all_novel_update'
          get 'hot'
          get 'this_week_hot'
          get 'this_month_hot'
          get 'search'
          get 'elastic_search'
          get 'classic'
          get 'classic_action'
          get 'collect_novels_info'
          get 'recommend_category_novels'
          get 'new_uploaded_novels'
        end
        member do 
          get 'detail_for_save'
        end
      end
      resources :articles,:only => [:index, :show] do
        collection do 
          get 'next_article'
          get 'previous_article'
          get 'articles_by_num'
          get 'next_article_by_num'
          get 'previous_article_by_num'
          # get 'db_transfer_index'
        end
      end

      resources :users, :only => [:create] do
        collection do
          put 'update_novel'
          get 'get_novels'
          get 'back_up_info'
        end
      end
    end
  end
end

app/models/novel.rb
class Novel < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  attr_accessible :name, :author, :description, :pic, :category_id, :article_num, :last_update, :is_serializing, :is_category_recommend, :is_category_hot, :is_category_this_week_hot, :is_classic, :is_classic_action, :is_show, :link
  belongs_to :category
  has_many :articles

  scope :show, where(:is_show => true)

  mapping do
    indexes :name, type: 'string'
    indexes :author, type: 'string'
  end

  def as_indexed_json(options={})
    self.as_json(only: [:name,:author])
  end

  after_create :create_index
  after_update :update_index
  after_destroy :delete_index

  def recrawl_articles_text
    Article.where("novel_id = #{id} and is_show = true").select("id").find_in_batches(:batch_size => 100) do |articles|
      articles.each do |article|
        texts = ArticleText.select("id").where("article_id = #{article.id}")
        unless texts.present?
          if link.index('33yq')
            YqArticleWorker.perform_async(article.id)
          else
            ArticleWorker.perform_async(article.id)
          end
        end 
      end 
    end
  end

  def update_num
    self.article_num = articles.show.size.to_s + "篇"
    self.save
  end

  def create_index
    __elasticsearch__.index_document
  end

  def update_index
    __elasticsearch__.update_document
  end

  def delete_index
    __elasticsearch__.delete_document
  end
end

app/controllers/api/v1/novels_controller.rb
class Api::V1::NovelsController < Api::ApiController

  def new_uploaded_novels
    novels = Novel.show.select("id,name,author,pic,article_num,last_update,is_serializing").order("created_at DESC").paginate(:page => params[:page], :per_page => 50)
    render :json => novels
  end

  def recommend_category_novels
    category_id = params[:recommend_category_id]
    category = RecommendCategory.find(category_id)
    novels = category.novels.select("novels.id,name,author,pic,article_num,last_update,is_serializing").shuffle
    render :json => novels
  end

  def collect_novels_info 
    novels_id = params[:novels_id]
    novels = Novel.where("id in (#{novels_id})").select("id,name,author,pic,article_num,last_update,is_serializing")
    render :json => novels
  end

  def index
    category_id = params[:category_id]
    unless category_id == "13"
      categoryies_id = find_same_set_ids(category_id)
      novels = Novel.where('category_id in (?)', categoryies_id).show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50)
    else
      novels = Novel.where('is_serializing = false').show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50)
    end
    render :json => novels
  end

  def show
    novel = Novel.find(params[:id])
    render :json => novel
  end

  def category_hot
    category_id = params[:category_id]
    unless category_id == "13"
      categoryies_id = find_same_set_ids(category_id)
      novels = Novel.where('category_id in (?) and is_category_hot = true', categoryies_id).show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    else
      novels = Novel.where('is_serializing = false and is_category_hot = true').show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    end
    render :json => novels
  end

  def category_this_week_hot
    category_id = params[:category_id]
    unless category_id == "13"
      categoryies_id = find_same_set_ids(category_id)
      novels = Novel.where('category_id in (?) and is_category_this_week_hot = true', categoryies_id).show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    else
      novels = Novel.where('is_serializing = false and is_category_this_week_hot = true').show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    end
    render :json => novels
  end

  def category_recommend
    category_id = params[:category_id]
    unless category_id == "13"
      categoryies_id = find_same_set_ids(category_id)
      novels = Novel.where('category_id in (?) and is_category_recommend = true', categoryies_id).show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    else
      novels = Novel.where('is_serializing = false and is_category_recommend = true').show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    end
    render :json => novels
  end

  def category_latest_update
    category_id = params[:category_id]
    unless category_id == "13"
      categoryies_id = find_same_set_ids(category_id)
      novels = Novel.where('category_id in (?)', categoryies_id).show.select("id,name,author,pic,article_num,last_update,is_serializing").order("updated_at DESC").paginate(:page => params[:page], :per_page => 50)
    else
      novels = Novel.where('is_serializing = false').order("updated_at DESC").show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50)
    end
    render :json => novels
  end

  def category_finish
    category_id = params[:category_id]
    categoryies_id = find_same_set_ids(category_id)
    novels = Novel.where('is_serializing = false and category_id in (?)', categoryies_id).show.select("id,name,author,pic,article_num,last_update,is_serializing").order("updated_at DESC").paginate(:page => params[:page], :per_page => 50)
  
    render :json => novels
  end

  def hot
    novels_id = HotShip.all.map{|ship| ship.novel_id}.join(',')
    novels = Novel.where("id in (#{novels_id})").show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    render :json => novels
  end

  def this_week_hot
    novels_id = ThisWeekHotShip.all.map{|ship| ship.novel_id}.join(',')
    novels = Novel.where("id in (#{novels_id})").show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    render :json => novels
  end

  def this_month_hot
    novels_id = ThisMonthHotShip.all.map{|ship| ship.novel_id}.join(',')
    novels = Novel.where("id in (#{novels_id})").show.select("id,name,author,pic,article_num,last_update,is_serializing").paginate(:page => params[:page], :per_page => 50).order("updated_at DESC")
    render :json => novels
  end

  def all_novel_update
    novels = Novel.show.select("id,name,author,pic,article_num,last_update,is_serializing").order("updated_at DESC").paginate(:page => params[:page], :per_page => 50)
    render :json => novels
  end

  def search
    keyword = params[:search].strip
    keyword_cn = keyword.clone
    keyword_cn = ZhConv.convert("zh-tw",keyword_cn,false)
    novels = Novel.where("name like ? or author like ? or name like ? or author like ?", "%#{keyword}%","%#{keyword}%","%#{keyword_cn}%","%#{keyword_cn}%").show.select("id,name,author,pic,article_num,last_update,is_serializing")
    render :json => novels
  end

  def elastic_search
    keyword = params[:search].strip
    keyword_cn = keyword.clone
    keyword_cn = ZhConv.convert("zh-tw",keyword_cn,false)
    novels = Novel.search(keyword_cn).per_page(20).page(params[:page])
    render :json => novels.records.where(is_show: true).select("id,name,author,pic,article_num,last_update,is_serializing")
  end

  def detail_for_save
    @novel = Novel.find(params[:id])
    render :json => { "novel" =>  @novel }
    # @articles = Article.where("novel_id = #{@novel.id}").select("id, subject, title")
  end

  
  def classic
    novels = Novel.where('is_classic = true').show.select("id,name,author,pic,article_num,last_update,is_serializing")
    render :json => novels
  end

  def classic_action
    novels = Novel.where('is_classic_action = true').show.select("id,name,author,pic,article_num,last_update,is_serializing")
    render :json => novels
  end

private
  def find_same_set_ids(category_id)
    case category_id
    when "14"
      [1,14]
    when "15"
      [2,15]
    when "16"
      [3,16]
    when "17"
      [9,17]
    when "18"
      [7,18]
    when "19"
      [5,19]
    when "20"
      [6,20]
    when "21"
      [21]
    when "22"
      [22,12]
    when "23"
      [8,23]
    when "24"
      [4,24]
    else
      [category_id.to_i]
    end
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :require_admin, only: [:new, :create, :edit, :update, :index, :show, :destroy]

  def index
    @novels = Novel.select("id,name,author,is_show,category_id").includes(:category).paginate(:page => params[:page], :per_page => 20)
  end

  def search
    keyword = params[:search].strip
    keyword_cn = keyword.clone
    keyword_cn = ZhConv.convert("zh-tw",keyword_cn,false)
    @novels = Novel.search(keyword_cn).per_page(100).records.includes(:category).select("id,name,author,pic,article_num,last_update,is_serializing,is_show,category_id")
  end

  def update_novel
    novel = Novel.find(params[:novel_id])
    redirect_to :action => 'show', :id => novel.id, :page => 1
  end

  def show
    @novel = Novel.find(params[:id])
    @articles = Article.select("articles.id,title,subject,num,is_show, novel_id").where("novel_id = #{params[:id]} and is_show = true").order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 50).order("num ASC")
    @websites = CrawlerAdapter.adapter_map
  end

  def invisiable_articles
    @novel = Novel.find(params[:id])
    @articles = Article.select("articles.id,title,subject,num,is_show, novel_id").where("novel_id = #{params[:id]} and is_show = false").order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 50).order("num ASC")
    @websites = CrawlerAdapter.adapter_map
  end

  def edit
    @novel = Novel.find(params[:id])
  end

  def destroy
    @novel = Novel.find(params[:id])
    Article.delete_all("novel_id = #{@novel.id}")
    @novel.destroy
    redirect_to :controller => 'novels', :action => 'index'
  end

  def new
    @novel = Novel.new
    @websites = CrawlerAdapter.adapter_map
  end

  def create
    @novel = Novel.new(params[:novel])
    @websites = CrawlerAdapter.adapter_map
    if @novel.save
      redirect_to :action => 'show', :id => @novel.id, :page => 1
    else
      render :action => "new"
    end
  end

  def update
    @novel = Novel.find(params[:id])
    if @novel.update_attributes(params[:novel])
      redirect_to :action => 'show', :page => 1
    else
      render :action => "edit" 
    end
  end

  def set_all_articles_to_invisiable
    Article.update_all("is_show = false", "novel_id = #{params[:id]}")
    novel = Novel.find(params[:id])
    novel.update_num
    redirect_to novel_path(params[:id])
  end

  def set_artlcles_to_invisiable
    Article.update_all("is_show = false","novel_id = #{params[:id]} and num >= #{params[:num_from]} and num <= #{params[:num_to]}")
    novel = Novel.find(params[:id])
    novel.update_num
    redirect_to novel_path(params[:id],page: params[:page])
  end

  def change
    novel = Novel.find(params[:id])
    novel.link = params[:link][:new_link]
    novel.num = params[:link][:num]
    novel.save
    f = FromLink.find_or_initialize_by_novel_id(params[:id])
    f.link = params[:link][:from_link]
    f.save

    CrawlWorker.perform_async(params[:id])

    # CrawlWorker.perform_async(params[:id])
    redirect_to novel_path(params[:id],page: 1)
  end

  def recrawl_all_articles
    CrawlWorker.perform_async(params[:id])
    redirect_to novel_path(params[:id],page: 1)
  end

  def recrawl_blank_articles
    novel = Novel.find(params[:id])
    novel.recrawl_articles_text
    redirect_to novel_path(params[:id])
  end

  def auto_crawl
    novel_link = params[:novel_link]
    crawler = CrawlerAdapter.get_instance novel_link
    crawler.fetch novel_link
    novel_id = crawler.crawl_novel(params[:category_id])
    redirect_to novel_path(novel_id)
  end

  private

  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "is_show"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/api/v1/novels_helper.rb
module Api::V1::NovelsHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/novels/_form.html.erb
小說名：　<%= @novel.name %> </br> 
作者:　　<%= @novel.author %> </br> 
<%= form_for "", :url => update_novel_novels_path, :method => :put do |f|%>

  <%= f.text_field "novel_id",:value => @novel.id,:type => "hidden" %><br />
  <%= f.label :parse_url %>:
  <%= f.text_field "url" %>
<%= f.submit "crawl" %>
<% end %>

app/views/novels/auto_crawl_info.html.erb
<br>
<%= form_for "", :url => auto_crawl_novels_path, :method => :put do |f|%>
  
  <%= f.label :novel_link %>:
  <%= f.text_field "novel_link" %><br>

  <%= f.label :category_id %>:
  <%= f.text_field :category_id %><br>
   10(名著古典),11(科普其它),14(玄幻魔法),15(武俠修真),16(都市言情),17(歷史軍事),18(游戲競技),19(科幻小說),20(恐怖靈異),21(美文散文),22(同人小說),23(輕小說),24(穿越重生)<br><br>

  <%= f.submit %>

<% end %>

<table>
  <tr>
    <th>網站</th>
    <th></th>
  </tr>

  <tr>
    <th>http://book.sfacg.com/</th>
  </tr>
  <tr>
    <th>http://xs.dmzj.com/</th>
  </tr>
  <tr>
    <th>http://www.uukanshu.com/</th>
  </tr>
  <tr>
    <th>http://www.piaotian.net/</th>
  </tr>
  <tr>
    <th>http://www.69shu.com/</th>
  </tr>
  <tr>
    <th>http://www.33yq.com/</th>
  </tr>
  <tr>
    <th>http://www.danmeila.com/</th>
  </tr>
</table>

app/views/novels/edit.html.erb
<ul>可以用的網站：
<li><%= link_to "http://www.bestory.com/","http://www.bestory.com/"%></li>
</ul>

<h1>修改novel :</h1>

<br>##############################換novel link ########################################<br>
請先把不要的articles set invisible<br>
<%= form_tag controller: "novels", action: "change",id: @novel, method: "post" do %>  
    新 novel link   
    <%= text_field :link,:new_link %><br>  
    從這篇 link 開始抓取
    <%= text_field :link,:from_link%><br>
    原本最後一篇article的num
    <%= text_field :link,:num%><br>
    <%= submit_tag 'Start' %>  
<% end %>  

<br>#########################################################################<br>

<%= form_for(@novel) do |f| %>

  <div class="actions">
    <%= f.label :name %>:
    <%= f.text_field :name %> <br>
    <%= f.label :author %>:
    <%= f.text_field :author %><br>
    <%= f.label :description %>:
    <%= f.text_area :description ,:cols => "400"%><br>
    <%= f.label :pic %>:
    <%= f.text_field :pic %><br>
    <%= f.label "category id" %>:
    <%= f.text_field :category_id %> 10(名著古典),11(科普其它),14(玄幻魔法),15(武俠修真),16(都市言情),17(歷史軍事),18(游戲競技),19(科幻小說),20(恐怖靈異),21(美文散文),22(同人小說),23(輕小說),24(穿越重生) <br>
    <%= f.label :article_num %>:
    <%= f.text_field :article_num %> 給一個大概的集數<br>
    <%= f.label :last_update %>:
    <%= f.text_field :last_update %> ex: 12-06-01 <br>
    <%= f.label :is_serializing %>:
    <%= f.text_field :is_serializing %> 0(全本)1(連載中)<br>
    <%= f.label :is_category_recommend %>:
    <%= f.text_field :is_category_recommend %><br>
    <%= f.label :is_category_hot %>:
    <%= f.text_field :is_category_hot %><br>
    <%= f.label :is_category_this_week_hot %>:
    <%= f.text_field :is_category_this_week_hot %><br>
    <%= f.label :is_classic %>:
    <%= f.text_field :is_classic %> (經典小說)<br>
    <%= f.label :is_classic_action %>:
    <%= f.text_field :is_classic_action %>(經典武俠)<br>
    <%= f.label :is_show %>:
    <%= f.text_field :is_show %><br>
    Novel Link: <%= @novel.link %><br>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', novel_path(@novel, page: 1) %> |
<%= link_to 'Back', novels_path %>

app/views/novels/index.html.erb
<h1>Listing novels</h1>
<%= form_for "", :url => search_novels_path, :method => :put do |f|%>
<%= f.text_field "search" %><br />
<% end %>

<%= link_to "貼網址抓取小說", auto_crawl_info_novels_path %>


<%= will_paginate @novels %>
<table>
  <tr>
    <th>小說id</th>
    <th>小說類別</th>
    <th>小說名</th>
    <th>作者名</th>
    <th>show</th>
  </tr>

<% @novels.each do |novel| %>
  <tr>
    <td><%= novel.id %></td>
    <td><%= (novel.category)? novel.category.name : "沒有類別" %></td>
    <td><%= novel.name %></td>
    <td><%= novel.author %></td>
    <td><%= novel.is_show %></td>
    <td><%= link_to 'Show', novel_path(novel, page: 1) %></td>
    <td><%= link_to 'Edit', edit_novel_path(novel) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/novels/invisiable_articles.html.erb
<p id="notice"><%= notice %></p>
小說名：　<%= @novel.name %> </br> 
作者:　　<%= @novel.author %> </br> 
show:   <%= @novel.is_show %> </br>
<%= link_to 'Edit', edit_novel_path(@novel) %> |
<%= link_to 'Back', novels_path %>


<br>#########################################################################<br>


<% if @articles %>
<table>
  <tr>
    <th>分類</th>
    <th>篇名</th>
    <th><%= sortable "num","篇數" %></th>
    <th><%= sortable "is_show","show"%></th>
    <th></th>
  </tr>

<%= will_paginate @articles %>

<% @articles.each do |article| %>
  <tr>
    <td> <%= article.subject %> &nbsp&nbsp</td>
    <td> <%= article.title %></td>
    <td> <%= article.num %></td>
    <td> <%= article.is_show %></td>
    <td> <%= truncate(article.try(:article_all_text)) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'ReCrawl', re_crawl_articles_path({:article_id => article.id}), data: { confirm: 'Are you sure?' } %></td>
    <td>
    <%= form_for "", :url => crawl_text_onther_site_articles_path({:article_id => article.id}), data: { confirm: 'Are you sure?' }, :method => :put do |f|%>

    <%= f.label :parse_url %>:
    <%= f.text_field "url" %>
    <%= f.submit "crawl" %>
    <% end %>
    </td>
    
    <td>
    <%= form_for "", :url => reset_num_articles_path({:article_id => article.id,:novel_id => article.novel_id,:page => params[:page]}), :method => :put do |f|%>
    <%= f.text_field "num" %> ex: 22
    <%= f.submit "set" %>
    
    <% end %>
    </td>


<% end %>
</table>
<% end %>

app/views/novels/search.html.erb
<h1>Listing novels</h1>
<%= form_for "", :url => search_novels_path, :method => :put do |f|%>

<%= f.text_field "search" %><br />

<% end %>

<table>
  <tr>
    <th>小說id</th>
    <th>小說類別</th>
    <th>小說名</th>
    <th>作者名</th>
    <th>show</th>
  </tr>

<% @novels.each do |novel| %>
  <tr>
    <td><%= novel.id %></td>
    <td><%= novel.category.name if novel.category %></td>
    <td><%= novel.name %></td>
    <td><%= novel.author %></td>
    <td><%= novel.is_show %></td>
    <td><%= link_to 'Show', novel_path(novel, page: 1) %></td>
    <td><%= link_to 'Edit', edit_novel_path(novel) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/novels/show.html.erb
<p id="notice"><%= notice %></p>
小說名：　<%= @novel.name %> </br> 
作者:　　<%= @novel.author %> </br> 
show:   <%= @novel.is_show %> </br>
<%= link_to 'Edit', edit_novel_path(@novel) %> |
<%= link_to 'Back', novels_path %>
<br>#########################################################################<br>

1. use edit to set new novel index url <br>
2. <%= link_to "set_all_articles_to_invisiable", set_all_articles_to_invisiable_novel_path(@novel), data: { confirm: 'Are you sure?' } %> <br>
或者設定範圍
<%= form_for "", :url => set_artlcles_to_invisiable_novel_path(@novel,page: params[:page]), :method => :put do |f|%>
從(>=) 
<%= f.text_field "num_from" %><br />
到(<=)
<%= f.text_field "num_to" %><br />
<%= submit_tag "", :id => 'Scomit', :style => "display: none;" %>
<% end %>

3. <%= link_to "recrawl_all_articles(new articles)", recrawl_all_articles_novel_path(@novel), data: { confirm: 'Are you sure?' } %><br>
4. <%= link_to "recrawl_all_existed_articles_which_blank_text(existed articles)", recrawl_blank_articles_novel_path(@novel), data: { confirm: 'Are you sure?' } %> <br>
5. <%= link_to "invisiable articles", invisiable_articles_novel_path(@novel) %>

<br>#########################################################################<br>
找特定篇數文章：
請輸入篇數
<%= form_for "", :url => search_by_num_articles_path(:novel_id => @novel.id), :method => :put do |f|%>

<%= f.text_field "num" %><br />

<% end %>

<br>#########################################################################<br>
<br>
new article: <%= link_to 'New', new_article_path(:novel_id => @novel.id,:page => params[:page]) %> <br>
<br>

<% if @articles %>
<table>
  <tr>
    <th>分類</th>
    <th>篇名</th>
    <th><%= sortable "num","篇數" %></th>
    <th><%= sortable "is_show","show"%></th>
    <th></th>
  </tr>

<%= will_paginate @articles %>

<% @articles.each do |article| %>
  <tr>
    <td> <%= article.subject %> &nbsp&nbsp</td>
    <td> <%= article.title %></td>
    <td> <%= article.num %></td>
    <td> <%= article.is_show %></td>
    <td> <%= truncate(article.try(:article_all_text)) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'ReCrawl', re_crawl_articles_path({:article_id => article.id}), data: { confirm: 'Are you sure?' } %></td>
    <td>
    <%= form_for "", :url => crawl_text_onther_site_articles_path({:article_id => article.id}), data: { confirm: 'Are you sure?' }, :method => :put do |f|%>

    <%= f.label :parse_url %>:
    <%= f.text_field "url" %>
    <%= f.submit "crawl" %>
    <% end %>
    </td>
    
    <td>
    <%= form_for "", :url => reset_num_articles_path({:article_id => article.id,:novel_id => article.novel_id,:page => params[:page]}), :method => :put do |f|%>
    <%= f.text_field "num" %> ex: 22
    <%= f.submit "set" %>
    
    <% end %>
    </td>


<% end %>
</table>
<% end %>
<br>
new article: <%= link_to 'New', new_article_path(:novel_id => @novel.id,:page => params[:page]) %> <br>
<br>

<br>#########################################################################<br>

<table>
  <tr>
    <th>網站</th>
    <th>Google search(click to google search)</th>
    <th>能不能爬網站的文章列表</th>
    <th>推薦使用的網站</th>
    <th></th>
  </tr>

<% @websites.each do |website_name, info| %>
  <tr>
    <% url = info['pattern'][1..info['pattern'].length-4] %>
    <th><%= website_name %></th>
    <th><%= link_to url,"https://www.google.com/search?q=#{@novel.name}+site%3A#{url}",:target => "_blank" %></th>
    <th><%= info['crawl_site_articles'] %></th>
    <th><%= info['recommend'] %></th> 
  </tr>
<% end %>

</table>