config/routes.rb
require 'sidekiq/web'
NovelServer::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'novels#index'
  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  

  resources :novels do 
    collection do
      put 'search'
      put 'update_novel'
      get 'auto_crawl_info'
      put 'auto_crawl'
    end
    member do
      get 'invisiable_articles'
      get 'set_all_articles_to_invisiable'
      put 'set_artlcles_to_invisiable'
      post 'change'
      get 'recrawl_all_articles'
      get 'recrawl_blank_articles'
    end
  end

  resources :articles do
    collection do
      get 're_crawl'
      put 'crawl_text_onther_site'
      put 'reset_num'
      put 'search_by_num'
    end
  end

  resources :ships, except: [:index,:show] do
    collection do
      get 'this_week_hot'
      get 'this_month_hot'
      get 'hot'
    end
  end

  resources :recommend_categories
  resources :recommend_category_novel_ships


  namespace :api do
    get 'status_check' => 'api#status_check'
    get 'version_check' => 'api#version_check'
    namespace :v1 do

      resources :recommend_categories, only: [:index]
      resources :categories, :only => [:index]
      resources :novels,:only => [:index, :show] do
        collection do
          get 'category_hot'
          get 'category_this_week_hot'
          get 'category_recommend'
          get 'category_latest_update'
          get 'category_finish'
          get 'all_novel_update'
          get 'hot'
          get 'this_week_hot'
          get 'this_month_hot'
          get 'search'
          get 'elastic_search'
          get 'classic'
          get 'classic_action'
          get 'collect_novels_info'
          get 'recommend_category_novels'
          get 'new_uploaded_novels'
        end
        member do 
          get 'detail_for_save'
        end
      end
      resources :articles,:only => [:index, :show] do
        collection do 
          get 'next_article'
          get 'previous_article'
          get 'articles_by_num'
          get 'next_article_by_num'
          get 'previous_article_by_num'
          # get 'db_transfer_index'
        end
      end

      resources :users, :only => [:create] do
        collection do
          put 'update_novel'
          get 'get_novels'
          get 'back_up_info'
        end
      end
    end
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController  

  def this_week_hot
    @ships = ThisWeekHotShip.includes(:novel).order("id desc").all
  end

  def this_month_hot
    @ships = ThisMonthHotShip.includes(:novel).order("id desc").all
    render :this_week_hot
  end

  def hot
    @ships = HotShip.includes(:novel).order("id desc").all
    render :this_week_hot
  end

  def destroy
    if(params[:ship_type] == "ThisMonthHotShip")
      ThisMonthHotShip.find(params[:id]).destroy
      redirect_to this_month_hot_ships_path
    elsif (params[:ship_type] == "ThisWeekHotShip")
      ThisWeekHotShip.find(params[:id]).destroy
      redirect_to this_week_hot_ships_path
    elsif (params[:ship_type] == "HotShip")
      HotShip.find(params[:id]).destroy
      redirect_to hot_ships_path
    end
  end

  def new
    @ship = eval (params[:ship_type] + ".new")
  end

  def create
    @ship = eval (params[:ship_type] + ".new")
    @ship.novel_id = params[:novel_id]
    @ship.save

    if(params[:ship_type] == "ThisMonthHotShip")
      redirect_to this_month_hot_ships_path
    elsif (params[:ship_type] == "ThisWeekHotShip")
      redirect_to this_week_hot_ships_path
    elsif (params[:ship_type] == "HotShip")
      redirect_to hot_ships_path
    end
  end
end

app/views/ships/new.html.erb
<h1>新增小說</h1>

<%= form_for "", url: ships_path do |f| %>
    <%= f.text_field :ship_type, value: params[:ship_type],:type => "hidden" %><br>
    <%= f.label "小說id" %>:
    <%= f.text_field :novel_id %>

    <%= f.submit "新增"%>
<% end %>

<br>
<br>
<br>

app/views/ships/this_week_hot.html.erb
<h1>Listing novels</h1>

<br>
<br>
<table>
  <tr>
    <th>新增的順序</th>
    <th>推薦書名</th>
    <th>類別名</th>
    <th>書id</th>
  </tr>

<%= link_to '新增小說', new_ship_path(ship_type: @ships[0].class.name) %> <br>

<% @ships.each do |ship| %>
  <tr>
    <% if ship.novel  %>
      <td><%= ship.id %></td>
      <td><%= ship.novel.name %></td>
      <td><%= (ship.novel.category)? ship.novel.category.name : "沒有類別" %></td>
      <td><%= ship.novel.id %></td>
      <td><%= link_to 'Destroy', ship_path(ship,ship_type: ship.class.name), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%else %>
      <%= ship.id %>
      <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新增小說', new_ship_path(ship_type: @ships[0].class.name) %> <br>